### PR TITLE
Added check for cash. Player connot buy licence without the fonds.

### PR DESCRIPTION
**Pull request by Pyth3rEx**
Player now require the cash before taking a test.
Provided new notification in English and French.

### CODE REVIEW

**Comment by Pyth3rEx** [comment]
Finaly got it to work ^^

**Comment by ElPumpo** [comment]
Not merging, you're not even following the correct indenting? Check your changes damnit.

**Comment by Pyth3rEx** [comment]
I'm spending time and work trying to help out the community with enhancements. If that's the way you want to play it so be it. But I'm not willing to work with the lack of respect you have.

**Comment by ElPumpo** [comment]
Sorry if my comment was respectless, it wasn't my intention.

Basicly your PR isn't up to our standards, but feel free to improve the code based off our feedback.

**Pull request closed without merging**
